POST http://localhost:4000/api/v1/categories/categoryAttributes/
Content-Type: application/json

{
    "name": "Thuong hieu",
    "categoryId": 1035,
    "value": [
        {
            "originName" : "Vietnam"
        },
        {
            "originName" : "Thai lan"
        }
    ],
    "formName": "Xuất xứ",
    "formType": "Select",
    "require": true,
    "slug": "xuat-xu"
}
