POST http://localhost:4000/api/v1/users/signup
Content-Type: application/json

{
    "username": "duongthanhphu123",
    "email": "",  
    "password": "phudk123",
    "fullName": "Duong Thanh Phu"
}


